# CMake generated Testfile for 
# Source directory: /home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/blas/testing
# Build directory: /home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/buid_dir/blas/testing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(sblat1 "/home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/blas/testing/runblastest.sh" "sblat1" "/home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/blas/testing/sblat1.dat")
add_test(sblat2 "/home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/blas/testing/runblastest.sh" "sblat2" "/home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/blas/testing/sblat2.dat")
add_test(sblat3 "/home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/blas/testing/runblastest.sh" "sblat3" "/home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/blas/testing/sblat3.dat")
add_test(dblat1 "/home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/blas/testing/runblastest.sh" "dblat1" "/home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/blas/testing/dblat1.dat")
add_test(dblat2 "/home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/blas/testing/runblastest.sh" "dblat2" "/home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/blas/testing/dblat2.dat")
add_test(dblat3 "/home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/blas/testing/runblastest.sh" "dblat3" "/home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/blas/testing/dblat3.dat")
add_test(cblat1 "/home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/blas/testing/runblastest.sh" "cblat1" "/home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/blas/testing/cblat1.dat")
add_test(cblat2 "/home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/blas/testing/runblastest.sh" "cblat2" "/home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/blas/testing/cblat2.dat")
add_test(cblat3 "/home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/blas/testing/runblastest.sh" "cblat3" "/home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/blas/testing/cblat3.dat")
add_test(zblat1 "/home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/blas/testing/runblastest.sh" "zblat1" "/home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/blas/testing/zblat1.dat")
add_test(zblat2 "/home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/blas/testing/runblastest.sh" "zblat2" "/home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/blas/testing/zblat2.dat")
add_test(zblat3 "/home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/blas/testing/runblastest.sh" "zblat3" "/home/leon/work/myHub/udacity-project/step1/lesson23_Extended_Kalman_Filters/eigen-eigen-323c052e1731/blas/testing/zblat3.dat")
